name: cidas-badger-catalog
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - matplotlib
  - pandas
  - obspy
  - jupyter
  - notebook
  - scipy
  - h5py
  - pytorch
  - pip
  - pip:
    - ipykernel
    - seisbench
    - elep
    - pyocto
    - libcomcat
