[project]
name = "cidas-badger-earthquake-catalog"
version = "0.1.0"
description = "Scripts to detect, locate, and characterize earthquakes using broadbands+DAS in Cook Inlet"
authors = ["Denolle-Lab"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.9"
numpy = "*"
matplotlib = "*"
pandas = "*"
obspy = "*"
jupyter = "*"
notebook = "*"
scipy = "*"
h5py = "*"
ipykernel = "*"
pytorch = "*"

[pypi-dependencies]
seisbench = "*"
elep = "*"
pyocto = "*"
usgs-libcomcat = "*"

[tasks]
jupyter = "jupyter notebook"
lab = "jupyter lab"
